name: asv_client
description: ASV Client App.
publish_to: 'none'
version: 1.0.50+50

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  socket_io_client: ^2.0.2
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_webrtc: ^0.9.26
  flutter_fadein: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

