name: asv_client
description: Free chat and video calls
publish_to: 'none'
version: 1.0.59+59

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.2
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_webrtc: ^0.9.48+hotfix.1
  flutter_background: ^1.0.0
  flutter_fadein: ^2.0.0
  envied: ^0.3.0
  uuid: ^3.0.7
  get_storage: ^2.1.1
  package_info_plus: ^3.1.2


dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


